### ISSUE TITLE
make this repository private

### ISSUE THREAD

**Issue by Damper1** [KartikeySharma/eyantra_task2#1]
hello guys I have noticed. 3-10 members is copying your code. make this repository as private. because everyone will use your code and ull get plagiarism. then you'll be eliminated from competition.

**Comment by KartikeySharma** [comment]
Hi @Damper1 
I didn't know about that. I had created this repository so that all of my team members can contribute actively and have the updated files and I uploaded this after task2 ended.
I am making this repository private and will surely keep that in mind in the next task.
Thanks :)
